name: Deploy to Cloud Run
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - uses: google-github-actions/setup-gcloud@v2

      - run: gcloud auth configure-docker

      - run: |
          docker build -t gcr.io/sublime-lodge-472322-m2/x-bot:latest .
          docker push gcr.io/sublime-lodge-472322-m2/x-bot:latest
          gcloud run deploy x-bot \
            --image gcr.io/sublime-lodge-472322-m2/x-bot:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --clear-env-vars \
            --set-env-vars "GOOGLE_CLOUD_PROJECT=sublime-lodge-472322-m2" \
            --memory 1Gi \
            --cpu 1 \
            --min-instances 1 \
            --max-instances 3
